version: 2

registries:
  npm-ghp:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GPR_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-ghp
    schedule:
      interval: "daily"
